name: Upload Helms to S3

on:
  push:
    branches: [ "main" ]
    paths:
      - docs/**

permissions:
  id-token: write
  contents: read

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::700774957897:role/GitHubActionsRole
          aws-region: eu-west-1

      - name: Sync docs to S3
        run: |
          aws s3 sync docs s3://helm-deployment-library/ --delete
